In [1]:
import numpy as np
#from sklearn.naive_bayes import MultinomialNB

import pandas as pd

df = pd.read_csv('dataset.csv')
df.head()

  Label                                       Error_List
0     T                  java.lang.nullpointer.exception
1     T               Array.index.out.of.bound.exception
2     F                         com.omsa.bound.exception
3     T                       com.omsa.service.exception
4     T  java.lang.nullpointer.exception.Stacktrce error

In [2]:
df.shape

(30, 2)

In [3]:
import string
df['Label'].value_counts()

T    25
F     5
Name: Label, dtype: int64

In [4]:
from nltk.corpus import stopwords

stopWords = set(stopwords.words('english'))
#print(stopWords)

import string
def text_cleaning(a):
 remove_punctuation = [char for char in a if char not in string.punctuation]
 #print(remove_punctuation)
 remove_punctuation=''.join(remove_punctuation)
 #print(remove_punctuation)   
 return [word for word in remove_punctuation.split() if word.lower() not in stopwords.words('english')]

In [5]:

from sklearn.feature_extraction.text import CountVectorizer
bow_transformer = CountVectorizer(analyzer=text_cleaning).fit(df['Error_List']) 
  
#print(len(bow_transformer.vocabulary_))   
bow_transformer.vocabulary_

{'javalangnullpointerexception': 30,
 'Arrayindexoutofboundexception': 1,
 'comomsaboundexception': 13,
 'comomsaserviceexception': 15,
 'javalangnullpointerexceptionStacktrce': 31,
 'error': 22,
 'comomsaboundexceptionba': 14,
 'deb': 19,
 'jpa': 32,
 'exception': 23,
 'UI': 7,
 'validation': 45,
 'message': 34,
 'Exception': 3,
 'happening': 27,
 'due': 20,
 'enabler': 21,
 'Runtime': 5,
 'exceuting': 24,
 'program': 41,
 'Throwable': 6,
 'com': 12,
 'omsa': 37,
 'service': 43,
 'java': 29,
 'lang': 33,
 'nullpointer': 36,
 'Array': 0,
 'index': 28,
 'bound': 10,
 'boundexception': 11,
 'ba': 8,
 'handling': 26,
 'bancs': 9,
 'Bancs': 2,
 'Please': 4,
 'retry': 42,
 'orgspringframeworkormjpa': 39,
 'orgspringframeworkormjpaJpaSystemException': 40,
 'could': 17,
 'execute': 25,
 'statement': 44,
 'nested': 35,
 'orghibernateexceptionGenericJDBCException': 38,
 'data': 18,
 'correct': 16}

In [6]:
tokens = bow_transformer.get_feature_names()
print(tokens)

['Array', 'Arrayindexoutofboundexception', 'Bancs', 'Exception', 'Please', 'Runtime', 'Throwable', 'UI', 'ba', 'bancs', 'bound', 'boundexception', 'com', 'comomsaboundexception', 'comomsaboundexceptionba', 'comomsaserviceexception', 'correct', 'could', 'data', 'deb', 'due', 'enabler', 'error', 'exception', 'exceuting', 'execute', 'handling', 'happening', 'index', 'java', 'javalangnullpointerexception', 'javalangnullpointerexceptionStacktrce', 'jpa', 'lang', 'message', 'nested', 'nullpointer', 'omsa', 'orghibernateexceptionGenericJDBCException', 'orgspringframeworkormjpa', 'orgspringframeworkormjpaJpaSystemException', 'program', 'retry', 'service', 'statement', 'validation']

In [7]:
title_bow = bow_transformer.transform(df['Error_List'])

print(title_bow)

  (0, 30)	1
  (1, 1)	1
  (2, 13)	1
  (3, 15)	1
  (4, 22)	1
  (4, 31)	1
  (5, 1)	1
  (6, 14)	1
  (7, 15)	1
  (7, 19)	1
  (8, 23)	1
  (8, 30)	1
  (8, 32)	1
  (9, 23)	1
  (9, 32)	1
  (10, 7)	1
  (10, 22)	1
  (10, 34)	1
  (10, 45)	1
  (11, 3)	1
  (11, 20)	1
  (11, 21)	1
  (11, 27)	1
  (12, 5)	1
  (12, 23)	1
  :	:
  (23, 43)	1
  (24, 9)	1
  (24, 20)	1
  (24, 22)	1
  (24, 26)	1
  (24, 27)	1
  (25, 2)	1
  (25, 4)	1
  (25, 42)	1
  (26, 22)	1
  (26, 45)	1
  (27, 39)	1
  (28, 17)	2
  (28, 23)	1
  (28, 25)	2
  (28, 35)	1
  (28, 38)	1
  (28, 40)	1
  (28, 44)	2
  (29, 16)	1
  (29, 17)	1
  (29, 18)	1
  (29, 20)	1
  (29, 25)	1
  (29, 44)	1

In [8]:
X = title_bow.toarray()
print(X)

 
X.shape  # 30,46  # 46 seperate words in our dataset and 30 rows

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 1 0]]

(30, 46)

In [9]:
# If you want you can store it in a dataframe also
dd=pd.DataFrame(data=title_bow.toarray(),columns=tokens)
dd

,Array,Arrayindexoutofboundexception,Bancs,Exception,Please,Runtime,Throwable,UI,ba,bancs,...,nullpointer,omsa,orghibernateexceptionGenericJDBCException,orgspringframeworkormjpa,orgspringframeworkormjpaJpaSystemException,program,retry,service,statement,validation
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
11,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
13,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
16,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
17,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
20,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
21,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
24,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
25,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,2,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [10]:
from sklearn.model_selection import train_test_split
#Splitting dataset into 90% training set and 10% test set
x_train, x_test, y_train, y_test = train_test_split(X, df.Label,test_size=0.1, random_state=50)

In [11]:
print(x_train.shape) # 27 rows and 46 columns as we have 46 different vocalublary 
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(27, 46)
(3, 46)
(27,)
(3,)

In [12]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB().fit(x_train,y_train)

In [13]:
prediction = model.predict(x_test)
print(prediction)

['T' 'T' 'F']

In [14]:
from sklearn.metrics import accuracy_score
#Printing accuracy of the our model
accuracy_score(prediction,y_test)

0.6666666666666666

In [15]:
y_test  #actual records of y_test

17    T
8     T
28    T
Name: Label, dtype: object

It have row number 17,8,28 and corresponding labels are True for all but our model predicited that the error at 28th row is not a error

# Testing on Unseen Data

In [16]:
user_data = ["java.lang.nullpointer.exception jpa exception"]
#user_data = "this is a demo.exception"
print(user_data)

['java.lang.nullpointer.exception jpa exception']

In [17]:
test_1_unseen =  bow_transformer.transform(user_data)
#pd.DataFrame(data=test_1_unseen.toarray(), columns=vocabulary)
data_4=test_1_unseen.toarray()
print("4: converted into array : \n ",data_4)

4: converted into array :
  [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0
  0 0 0 0 0 0 0 0 0 0]]

In [18]:
print("5: shape of array :  \n ",data_4.shape) #3,46  , 3 rows and 46 columns

5: shape of array :
  (1, 46)

In [19]:
prediction_unseen = model.predict(data_4)
print(prediction_unseen)

['T']

In [31]:
# updated dataset.csv file with this new error

import csv
with open('dataset.csv', 'a+', newline='') as file:
    writer = csv.writer(file)
    #writer.writerow(dataset)
    writer.writerow([prediction_unseen,user_data])